// <auto-generated />
namespace Lab1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changemaxlength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changemaxlength));
        
        string IMigrationMetadata.Id
        {
            get { return "201510172035074_change-max-length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
